version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: dev_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: deinDockerHubNutzername/portscanner-api:latest
    container_name: portscanner_api
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - postgres

  frontend:
    image: deinDockerHubNutzername/portscanner-ui:latest
    container_name: portscanner_ui
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
