name: Build and Push Python API

on:
  push:
    branches:
      - main
    paths:
      - 'PythonAPI/**'

jobs:
  push-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: ./PythonAPI
          push: true
          tags: t1me0n/lan-api:latest
